---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: no-commit-to-branch
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
  - id: yamllint
    args:
    - --strict
    - --config-file=.yamllint
